### ISSUE TITLE
How to deal with different Guava version than Jackson

### ISSUE THREAD

**Issue by Erwyn** [FasterXML/jackson-datatypes-collections#70]
Hello,

I encounter an issue but I guess this is more about me being not knowledgeable enough than the library doing something wrong.

In my `pom.xml` I have `jackson-datatypes-guava` at the version 2.11.2 and Guava at version 29-jre. The issue that arises is that when I call `ImmutableList.toImmutableList()` I have a no such method because it picks the `com.google.common.collect.ImmutableList` from Guava.

Do you have an indication on how to proceed ?

**Comment by cowtowncoder** [comment]
I am not sure I understand the issue with details given yet. Would it be possible to add the stack trace for failure you see?

**Comment by Erwyn** [comment]
Sure, so here is what I get as a failure:

```
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;
	at io.jenkins.plugins.tuleap_credentials.AccessKeyChecker.scopesAreValid(AccessKeyChecker.java:40)
	at io.jenkins.plugins.tuleap_credentials.AccessKeyChecker.verifyAccessKey(AccessKeyChecker.java:26)
	at ....
```

The incriminated method is here: https://github.com/google/guava/blame/master/guava/src/com/google/common/collect/ImmutableList.java#L70  and if the comment is correct, it's in there since 21.0 but Jackson-datatypes-guava uses 20.0.

I may be completely wrong and missing something obvious due to inexperience.

**Comment by cowtowncoder** [comment]
@Erwyn Ah. Ok, so, Jackson Guava module should currently work with all versions starting with 15.0, up to latest (29). So you should be able to define explicit Guava version you would like to use.

Guava module does specify a single "official" dependency version since version range handling has traditionally not worked well across tooling but we have tried to keep module as robust as possible since Guava version's in use vary a lot. It is a big problem in Java development space: popularity of Guava is both a bless and a curse (not unlike that of Jackson's :) ); downside being that it is a transitive dependency of most of Java OSS frameworks and libraries.

So: I think you will just need to add an explicit dependency to Guava version that works with other libraries -- it is bit odd that Jenkins plug-in in question does not bring in new enough version but maybe Maven decides to resolve it in that way for some reason.

**Comment by Erwyn** [comment]
@cowtowncoder thanks for taking the time.

I'm not sure to get what I should be doing.  Here is an extract of my pom.xml:

```
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>29.0-jre</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.11.2</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-guava</artifactId>
            <version>2.11.2</version>
        </dependency>   
```

So I'm already defining my guava version, or am I not? I need to do something else ?

**Comment by cowtowncoder** [comment]
@Erwyn Your build file looks fine to me. But I think you will need to figure out what is actually deployed: it probably is not version you specify, given the exception you see.
One thing to try first I guess is to see what `mvn dependency:tree` gives as build-time dependency version (should be 29.0-jre based on above). But after that, it depends on how thing you are running is packaged. I'd guess it contains an older Guava version.

**Comment by Erwyn** [comment]
Hi @cowtowncoder,

that's indeed strange, `mvn dependency:tree` gives me indeed back 29:

```
[INFO] +- com.google.guava:guava:jar:29.0-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:2.11.1:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.3.4:compile
[INFO] |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
```

**Comment by cowtowncoder** [comment]
@Erwyn right, but build time dependencies do not always become actual runtime inclusions: so while this is correct, the issue then is that during runtime Guava version in use is not 29.0-jre.

But this depends on how artifact to deploy is built: it could be a single "uber-jar" (but if so, it'd be more likely to contain correct version), or it may be provided by the platform. If this is running in Jenkins, it's Jenkins that actually provides Guava in classpath. And in fact it is also possible that there might be multiple guava jars in classpath (in which case version getting used is somewhat arbitrary).

**Comment by Erwyn** [comment]
@cowtowncoder thanks for the explanation.

Is there a way to determine which version is used on runtime and/or even select one or am I basically kind of stuck here?

**Comment by cowtowncoder** [comment]
@Erwyn I'm sure there is a way to resolve it but I can not help much further since I don't know anything about your build or deployment system, and there isn't much I think that Jackson could do to help.

**Comment by Erwyn** [comment]
Hi @cowtowncoder. Thank you very much for the provided help ! You're right, as this is not Jackson related, there is nothing you could do to help.

Thanks again, I close the issue :)
